"""
This type stub file was generated by pyright.
"""

import click
import rocks

"""rocks command line suite."""

class AliasedGroup(click.Group):
    """Click group with custom default mode implementation."""

    def get_command(self, ctx, cmd_name): ...

@click.group(cls=AliasedGroup)
@click.version_option(version=rocks.__version__, message="%(version)s")
def cli_rocks():  # -> None:
    """CLI for minor body exploration."""
    ...

@cli_rocks.command()
def docs():  # -> None:
    """Open rocks documentation in browser."""
    ...

@cli_rocks.command()
@click.argument("id_")
def id(id_):  # -> None:
    """Get asteroid name and number from string input."""
    ...

@cli_rocks.command()
@click.argument("id_")
def info(id_):  # -> None:
    """Print ssoCard of minor body."""
    ...

@cli_rocks.command()
def parameters():  # -> None:
    """Print the ssoCard and its description."""
    ...

@cli_rocks.command()
def status():  # -> None:
    """Echo the status of the ssoCards and datacloud catalogues."""
    ...

def echo(plot):  # -> NoReturn:
    """Echos asteroid parameter to command line. Optionally opens plot.

    Parameters
    ==========
    plot : bool
        If the paramter values should be plotted.
    """
    ...
